-- WOA seed: 20 realistic Canadian artist profiles
-- Run this in Supabase SQL Editor.
--
-- The script creates confirmed fake auth users first, then upserts matching
-- public.profiles rows. It is safe to run more than once.

create extension if not exists pgcrypto with schema extensions;

with seed_artists (
  id,
  email,
  username,
  full_name,
  avatar_url,
  discipline,
  art_types,
  country,
  city,
  experience,
  bio,
  instagram,
  website,
  is_available,
  follower_count,
  is_verified
) as (
  values
    (
      '3f97f47c-2222-48d7-a901-001f24a62001'::uuid,
      'imani.fraser.seed@workerofart.com',
      'imanifraser',
      'Imani Fraser',
      'https://ui-avatars.com/api/?name=Imani+Fraser&background=111111&color=ffffff&size=256&bold=true&format=png',
      'Photographer',
      array['Documentary Photography', 'Portrait Photography', 'Street Photography']::text[],
      'Canada',
      'Toronto',
      '9',
      'Documentary photographer making intimate portraits of neighbourhood life, family rituals, and young artists building their first bodies of work.',
      'imanifraser.photo',
      'https://imanifraser.example',
      true,
      344,
      true
    ),
    (
      '3f97f47c-2222-48d7-a901-001f24a62002'::uuid,
      'antoine.gagnon.seed@workerofart.com',
      'antoinegagnon',
      'Antoine Gagnon',
      'https://ui-avatars.com/api/?name=Antoine+Gagnon&background=111111&color=ffffff&size=256&bold=true&format=png',
      'Filmmaker',
      array['Short Film', 'Cinematography', 'Documentary']::text[],
      'Canada',
      'Montreal',
      '11',
      'Filmmaker and cinematographer drawn to quiet stories, handheld movement, and natural light. Available for shorts, music videos, and artist profiles.',
      'antoinegagnonfilm',
      'https://antoinegagnon.example',
      true,
      401,
      true
    ),
    (
      '3f97f47c-2222-48d7-a901-001f24a62003'::uuid,
      'meilin.park.seed@workerofart.com',
      'meilinpark',
      'Meilin Park',
      'https://ui-avatars.com/api/?name=Meilin+Park&background=111111&color=ffffff&size=256&bold=true&format=png',
      'Ceramicist',
      array['Ceramics', 'Tableware', 'Sculptural Objects']::text[],
      'Canada',
      'Vancouver',
      '7',
      'Ceramicist making soft-edged vessels and sculptural tableware inspired by rain, moss, and handwritten notes. Open to small batch collaborations.',
      'meilinpark.clay',
      'https://meilinpark.example',
      false,
      229,
      false
    ),
    (
      '3f97f47c-2222-48d7-a901-001f24a62004'::uuid,
      'samira.qureshi.seed@workerofart.com',
      'samiraqureshi',
      'Samira Qureshi',
      'https://ui-avatars.com/api/?name=Samira+Qureshi&background=111111&color=ffffff&size=256&bold=true&format=png',
      'Graphic Designer',
      array['Brand Identity', 'Editorial Design', 'Typography']::text[],
      'Canada',
      'Calgary',
      '8',
      'Graphic designer building identity systems for cultural projects, small businesses, festivals, and artists who need a strong visual language.',
      'samiraq.design',
      'https://samiraqureshi.example',
      true,
      318,
      false
    ),
    (
      '3f97f47c-2222-48d7-a901-001f24a62005'::uuid,
      'dawson.crow.seed@workerofart.com',
      'dawsoncrow',
      'Dawson Crow',
      'https://ui-avatars.com/api/?name=Dawson+Crow&background=111111&color=ffffff&size=256&bold=true&format=png',
      'Muralist',
      array['Public Art', 'Murals', 'Community Art']::text[],
      'Canada',
      'Regina',
      '13',
      'Muralist and community arts facilitator painting large-scale work about prairie memory, public space, and shared local stories.',
      'dawsoncrowmurals',
      'https://dawsoncrow.example',
      true,
      287,
      true
    ),
    (
      '3f97f47c-2222-48d7-a901-001f24a62006'::uuid,
      'elena.marino.seed@workerofart.com',
      'elenamarino',
      'Elena Marino',
      'https://ui-avatars.com/api/?name=Elena+Marino&background=111111&color=ffffff&size=256&bold=true&format=png',
      'Actor',
      array['Theatre', 'Film Acting', 'Voiceover']::text[],
      'Canada',
      'Halifax',
      '6',
      'Actor with theatre training and a love for character-driven indie film. Available for shorts, readings, voiceover, and devised performance.',
      'elenamarinoacts',
      'https://elenamarino.example',
      true,
      173,
      false
    ),
    (
      '3f97f47c-2222-48d7-a901-001f24a62007'::uuid,
      'callum.oreilly.seed@workerofart.com',
      'callumoreilly',
      'Callum O''Reilly',
      'https://ui-avatars.com/api/?name=Callum+OReilly&background=111111&color=ffffff&size=256&bold=true&format=png',
      'Musician',
      array['Folk', 'Guitar', 'Songwriting']::text[],
      'Canada',
      'St. John''s',
      '12',
      'Folk musician and songwriter writing weathered songs about distance, repair, and old houses. Open to scoring shorts and co-writing.',
      'callumoreillymusic',
      'https://callumoreilly.example',
      true,
      365,
      true
    ),
    (
      '3f97f47c-2222-48d7-a901-001f24a62008'::uuid,
      'noura.benali.seed@workerofart.com',
      'nourabenali',
      'Noura Benali',
      'https://ui-avatars.com/api/?name=Noura+Benali&background=111111&color=ffffff&size=256&bold=true&format=png',
      'Fashion Designer',
      array['Garment Design', 'Styling', 'Costume']::text[],
      'Canada',
      'Ottawa',
      '10',
      'Fashion designer making structured garments from reclaimed textiles. I style editorials, build custom performance looks, and collaborate with photographers.',
      'nourabenali.studio',
      'https://nourabenali.example',
      true,
      442,
      true
    ),
    (
      '3f97f47c-2222-48d7-a901-001f24a62009'::uuid,
      'evie.robitaille.seed@workerofart.com',
      'evierobitaille',
      'Evie Robitaille',
      'https://ui-avatars.com/api/?name=Evie+Robitaille&background=111111&color=ffffff&size=256&bold=true&format=png',
      'Illustrator',
      array['Editorial Illustration', 'Children''s Books', 'Comics']::text[],
      'Canada',
      'Quebec City',
      '9',
      'Illustrator making playful, detailed drawings for books, magazines, and small brands. I like strange animals, warm palettes, and expressive faces.',
      'evierobitaille.draws',
      'https://evierobitaille.example',
      false,
      254,
      false
    ),
    (
      '3f97f47c-2222-48d7-a901-001f24a62010'::uuid,
      'mateo.salazar.seed@workerofart.com',
      'mateosalazar',
      'Mateo Salazar',
      'https://ui-avatars.com/api/?name=Mateo+Salazar&background=111111&color=ffffff&size=256&bold=true&format=png',
      'DJ',
      array['DJ', 'Latin House', 'Event Sound']::text[],
      'Canada',
      'Winnipeg',
      '8',
      'DJ blending Latin house, disco, and warm club edits. Available for art openings, community events, dance floors, and collaborative sound projects.',
      'mateosalazar.wav',
      'https://mateosalazar.example',
      true,
      510,
      false
    ),
    (
      '3f97f47c-2222-48d7-a901-001f24a62011'::uuid,
      'harper.ng.seed@workerofart.com',
      'harperng',
      'Harper Ng',
      'https://ui-avatars.com/api/?name=Harper+Ng&background=111111&color=ffffff&size=256&bold=true&format=png',
      'Animator',
      array['2D Animation', 'Motion Design', 'Music Visuals']::text[],
      'Canada',
      'Edmonton',
      '5',
      'Animator and motion designer creating looping visuals, title cards, and playful short-form animation for musicians, filmmakers, and arts organizations.',
      'harperng.motion',
      'https://harperng.example',
      true,
      206,
      false
    ),
    (
      '3f97f47c-2222-48d7-a901-001f24a62012'::uuid,
      'rosa.martel.seed@workerofart.com',
      'rosamartel',
      'Rosa Martel',
      'https://ui-avatars.com/api/?name=Rosa+Martel&background=111111&color=ffffff&size=256&bold=true&format=png',
      'Dancer',
      array['Contemporary Dance', 'Choreography', 'Movement Direction']::text[],
      'Canada',
      'Moncton',
      '14',
      'Contemporary dancer and choreographer developing intimate performance work for galleries, outdoor sites, and small stages.',
      'rosamartelmoves',
      'https://rosamartel.example',
      true,
      390,
      true
    ),
    (
      '3f97f47c-2222-48d7-a901-001f24a62013'::uuid,
      'tomasz.nowak.seed@workerofart.com',
      'tomasznowak',
      'Tomasz Nowak',
      'https://ui-avatars.com/api/?name=Tomasz+Nowak&background=111111&color=ffffff&size=256&bold=true&format=png',
      'Sculptor',
      array['Sculpture', 'Installation', 'Woodworking']::text[],
      'Canada',
      'Saskatoon',
      '15',
      'Sculptor building quiet installations from wood, steel, and salvaged material. I like work that feels architectural, handmade, and slightly off-balance.',
      'tomasznowak.objects',
      'https://tomasznowak.example',
      false,
      221,
      true
    ),
    (
      '3f97f47c-2222-48d7-a901-001f24a62014'::uuid,
      'mira.patel.seed@workerofart.com',
      'mirapatel',
      'Mira Patel',
      'https://ui-avatars.com/api/?name=Mira+Patel&background=111111&color=ffffff&size=256&bold=true&format=png',
      'Makeup Artist',
      array['Makeup Artist', 'Editorial Beauty', 'SFX Makeup']::text[],
      'Canada',
      'Mississauga',
      '7',
      'Makeup artist working in clean beauty, bold editorial looks, and light SFX. I love collaborating with photographers, stylists, and performers.',
      'mirapatel.makeup',
      'https://mirapatel.example',
      true,
      275,
      false
    ),
    (
      '3f97f47c-2222-48d7-a901-001f24a62015'::uuid,
      'quentin.baird.seed@workerofart.com',
      'quentinbaird',
      'Quentin Baird',
      'https://ui-avatars.com/api/?name=Quentin+Baird&background=111111&color=ffffff&size=256&bold=true&format=png',
      'Writer',
      array['Screenwriting', 'Essay', 'Spoken Word']::text[],
      'Canada',
      'Victoria',
      '11',
      'Writer of short scripts, essays, and spoken-word pieces about place, masculinity, and awkward attempts at tenderness.',
      'quentinbairdwrites',
      'https://quentinbaird.example',
      true,
      309,
      false
    ),
    (
      '3f97f47c-2222-48d7-a901-001f24a62016'::uuid,
      'selena.kwan.seed@workerofart.com',
      'selenakwan',
      'Selena Kwan',
      'https://ui-avatars.com/api/?name=Selena+Kwan&background=111111&color=ffffff&size=256&bold=true&format=png',
      'Tattoo Artist',
      array['Tattoo Artist', 'Flash Design', 'Fine Line']::text[],
      'Canada',
      'Kelowna',
      '6',
      'Tattoo artist drawing fine-line botanicals, tiny symbols, and personal flash. I also design merch graphics and album illustrations.',
      'selenakwan.tattoos',
      'https://selenakwan.example',
      false,
      338,
      false
    ),
    (
      '3f97f47c-2222-48d7-a901-001f24a62017'::uuid,
      'arjun.sethi.seed@workerofart.com',
      'arjunsethi',
      'Arjun Sethi',
      'https://ui-avatars.com/api/?name=Arjun+Sethi&background=111111&color=ffffff&size=256&bold=true&format=png',
      'Producer',
      array['Music Production', 'Mixing', 'Sound Design']::text[],
      'Canada',
      'Brampton',
      '9',
      'Producer and sound designer working across R&B, experimental pop, and short film scores. I like textured drums and emotional vocal arrangements.',
      'arjunsethi.sound',
      'https://arjunsethi.example',
      true,
      478,
      true
    ),
    (
      '3f97f47c-2222-48d7-a901-001f24a62018'::uuid,
      'willow.adams.seed@workerofart.com',
      'willowadams',
      'Willow Adams',
      'https://ui-avatars.com/api/?name=Willow+Adams&background=111111&color=ffffff&size=256&bold=true&format=png',
      'Textile Artist',
      array['Textile Art', 'Weaving', 'Natural Dye']::text[],
      'Canada',
      'Whitehorse',
      '10',
      'Textile artist working with weaving, natural dyes, and slow hand processes. My pieces often begin with landscape notes and old family blankets.',
      'willowadams.textiles',
      'https://willowadams.example',
      true,
      191,
      false
    ),
    (
      '3f97f47c-2222-48d7-a901-001f24a62019'::uuid,
      'nikita.snow.seed@workerofart.com',
      'nikitasnow',
      'Nikita Snow',
      'https://ui-avatars.com/api/?name=Nikita+Snow&background=111111&color=ffffff&size=256&bold=true&format=png',
      'Visual Artist',
      array['Painting', 'Installation', 'Community Art']::text[],
      'Canada',
      'Yellowknife',
      '12',
      'Visual artist making paintings and installations about northern light, kinship, and the way stories travel through objects.',
      'nikitasnow.studio',
      'https://nikitasnow.example',
      false,
      256,
      true
    ),
    (
      '3f97f47c-2222-48d7-a901-001f24a62020'::uuid,
      'elias.okpik.seed@workerofart.com',
      'eliasokpik',
      'Elias Okpik',
      'https://ui-avatars.com/api/?name=Elias+Okpik&background=111111&color=ffffff&size=256&bold=true&format=png',
      'Videographer',
      array['Videography', 'Event Video', 'Artist Profiles']::text[],
      'Canada',
      'Iqaluit',
      '6',
      'Videographer documenting performances, community gatherings, and artist stories. I work light, fast, and with a lot of respect for place.',
      'eliasokpikvideo',
      'https://eliasokpik.example',
      true,
      147,
      false
    )
),
upsert_auth_users as (
  insert into auth.users (
    id,
    instance_id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    confirmation_sent_at,
    raw_app_meta_data,
    raw_user_meta_data,
    is_super_admin,
    created_at,
    updated_at,
    last_sign_in_at
  )
  select
    id,
    '00000000-0000-0000-0000-000000000000'::uuid,
    'authenticated',
    'authenticated',
    email,
    extensions.crypt('seeded-profile-only', extensions.gen_salt('bf')),
    now(),
    now(),
    '{"provider":"email","providers":["email"]}'::jsonb,
    jsonb_build_object(
      'username', username,
      'full_name', full_name,
      'avatar_url', avatar_url,
      'profile_photo_url', avatar_url,
      'role', 'ARTIST',
      'discipline', discipline,
      'art_types', art_types,
      'country', country,
      'city', city,
      'experience', experience,
      'bio', bio,
      'instagram', instagram,
      'website', website,
      'is_available', is_available
    ),
    false,
    now(),
    now(),
    now()
  from seed_artists
  on conflict (id) do update set
    email = excluded.email,
    raw_user_meta_data = excluded.raw_user_meta_data,
    updated_at = now()
  returning id
)
insert into public.profiles (
  id,
  username,
  full_name,
  avatar_url,
  art_type,
  city,
  country,
  bio,
  role,
  created_at,
  profile_photo_url,
  experience,
  instagram,
  facebook,
  website,
  follower_count,
  rating,
  rating_count,
  tags,
  available_for_gigs,
  spotify,
  push_token,
  discipline,
  art_types,
  is_available,
  spotify_url,
  is_verified,
  verified_since,
  stripe_subscription_id,
  collective_type,
  member_count,
  booked_count
)
select
  id,
  username,
  full_name,
  avatar_url,
  discipline,
  city,
  country,
  bio,
  'ARTIST',
  now(),
  avatar_url,
  experience,
  instagram,
  null,
  website,
  follower_count,
  0,
  0,
  art_types,
  is_available,
  null,
  null,
  discipline,
  art_types,
  is_available,
  null,
  is_verified,
  case when is_verified then now() else null end,
  null,
  null,
  null,
  0
from seed_artists
on conflict (id) do update set
  username = excluded.username,
  full_name = excluded.full_name,
  avatar_url = excluded.avatar_url,
  art_type = excluded.art_type,
  city = excluded.city,
  country = excluded.country,
  bio = excluded.bio,
  role = excluded.role,
  profile_photo_url = excluded.profile_photo_url,
  experience = excluded.experience,
  instagram = excluded.instagram,
  website = excluded.website,
  follower_count = excluded.follower_count,
  rating = excluded.rating,
  rating_count = excluded.rating_count,
  tags = excluded.tags,
  available_for_gigs = excluded.available_for_gigs,
  discipline = excluded.discipline,
  art_types = excluded.art_types,
  is_available = excluded.is_available,
  is_verified = excluded.is_verified,
  verified_since = excluded.verified_since,
  booked_count = excluded.booked_count;
